name: Deploy Lambda Function

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies for Lambda layer
        run: |
          mkdir -p python
          pip install --upgrade pip
          pip install -r requirements.txt -t python

      - name: Package Lambda layer
        run: |
          zip -r lambda_layer.zip python

      - name: Package Lambda function
        run: |
          zip -r lambda_function.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Create/Update Lambda layer
        run: |
          LAYER_VERSION=$(aws lambda publish-layer-version \
            --layer-name my-lambda-layer \
            --zip-file fileb://lambda_layer.zip \
            --compatible-runtimes python3.12 \
            --query Version --output text)
          echo "LAYER_VERSION=$LAYER_VERSION" >> $GITHUB_ENV

      - name: Deploy Lambda function for dev branch
        if: github.ref == 'refs/heads/dev'
        run: |
          aws lambda update-function-code --function-name et_forecast_func_test --zip-file fileb://lambda_function.zip
          aws lambda update-function-configuration --function-name et_forecast_func_test --layers arn:aws:lambda:us-east-2:${{ secrets.AWS_ACCOUNT_ID }}:layer:my-lambda-layer:$LAYER_VERSION

      - name: Deploy Lambda function for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          aws lambda update-function-code --function-name et-forecast-func --zip-file fileb://lambda_function.zip
          aws lambda update-function-configuration --function-name et-forecast-func --layers arn:aws:lambda:us-east-2:${{ secrets.AWS_ACCOUNT_ID }}:layer:my-lambda-layer:$LAYER_VERSION
