name: Deploy Lambda Function

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Package Lambda function
        run: |
          zip -r lambda_function.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy Lambda function for dev branch
        if: github.ref == 'refs/heads/dev'
        run: |
          aws lambda update-function-code --function-name et_forecast_func_test --zip-file fileb://lambda_function.zip

      - name: Deploy Lambda function for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          aws lambda update-function-code --function-name et-forecast-func --zip-file fileb://lambda_function.zip
